# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
sudo: false
cache: packages
os:
  - linux
  - osx
script
  - Rscript -e 'library(devtools);devtools::install_github("RGLab/scamp");'