// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cppNoisyScamp
Rcpp::List cppNoisyScamp(Rcpp::NumericMatrix& rawDataMatrix, double dipT, int clusterLB, bool repeatsAllowed, int maxSearchDepth, long maxClusterNum, Rcpp::StringVector userAnnotations, long maxNumberOfGates, bool randomSearch, bool randomResidualSearch, const std::vector<double>& finalAnnotationQs, int numThreadsRequested, bool useRestrictedValue, Rcpp::NumericMatrix& restrictedValueMatrix, bool useForestValues, Rcpp::List forestValues, int numberOfScampIterations, std::string outputDirectory, bool verboseOutput, double maxSearchTime, bool debugScampRun, double gaussianScale, unsigned long long randomSeed, double depthScoreThreshold, unsigned long subSampleThreshold, unsigned long subSampleSize, unsigned long subSampleIterations);
RcppExport SEXP _scamp_cppNoisyScamp(SEXP rawDataMatrixSEXP, SEXP dipTSEXP, SEXP clusterLBSEXP, SEXP repeatsAllowedSEXP, SEXP maxSearchDepthSEXP, SEXP maxClusterNumSEXP, SEXP userAnnotationsSEXP, SEXP maxNumberOfGatesSEXP, SEXP randomSearchSEXP, SEXP randomResidualSearchSEXP, SEXP finalAnnotationQsSEXP, SEXP numThreadsRequestedSEXP, SEXP useRestrictedValueSEXP, SEXP restrictedValueMatrixSEXP, SEXP useForestValuesSEXP, SEXP forestValuesSEXP, SEXP numberOfScampIterationsSEXP, SEXP outputDirectorySEXP, SEXP verboseOutputSEXP, SEXP maxSearchTimeSEXP, SEXP debugScampRunSEXP, SEXP gaussianScaleSEXP, SEXP randomSeedSEXP, SEXP depthScoreThresholdSEXP, SEXP subSampleThresholdSEXP, SEXP subSampleSizeSEXP, SEXP subSampleIterationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type rawDataMatrix(rawDataMatrixSEXP);
    Rcpp::traits::input_parameter< double >::type dipT(dipTSEXP);
    Rcpp::traits::input_parameter< int >::type clusterLB(clusterLBSEXP);
    Rcpp::traits::input_parameter< bool >::type repeatsAllowed(repeatsAllowedSEXP);
    Rcpp::traits::input_parameter< int >::type maxSearchDepth(maxSearchDepthSEXP);
    Rcpp::traits::input_parameter< long >::type maxClusterNum(maxClusterNumSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type userAnnotations(userAnnotationsSEXP);
    Rcpp::traits::input_parameter< long >::type maxNumberOfGates(maxNumberOfGatesSEXP);
    Rcpp::traits::input_parameter< bool >::type randomSearch(randomSearchSEXP);
    Rcpp::traits::input_parameter< bool >::type randomResidualSearch(randomResidualSearchSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type finalAnnotationQs(finalAnnotationQsSEXP);
    Rcpp::traits::input_parameter< int >::type numThreadsRequested(numThreadsRequestedSEXP);
    Rcpp::traits::input_parameter< bool >::type useRestrictedValue(useRestrictedValueSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type restrictedValueMatrix(restrictedValueMatrixSEXP);
    Rcpp::traits::input_parameter< bool >::type useForestValues(useForestValuesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type forestValues(forestValuesSEXP);
    Rcpp::traits::input_parameter< int >::type numberOfScampIterations(numberOfScampIterationsSEXP);
    Rcpp::traits::input_parameter< std::string >::type outputDirectory(outputDirectorySEXP);
    Rcpp::traits::input_parameter< bool >::type verboseOutput(verboseOutputSEXP);
    Rcpp::traits::input_parameter< double >::type maxSearchTime(maxSearchTimeSEXP);
    Rcpp::traits::input_parameter< bool >::type debugScampRun(debugScampRunSEXP);
    Rcpp::traits::input_parameter< double >::type gaussianScale(gaussianScaleSEXP);
    Rcpp::traits::input_parameter< unsigned long long >::type randomSeed(randomSeedSEXP);
    Rcpp::traits::input_parameter< double >::type depthScoreThreshold(depthScoreThresholdSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type subSampleThreshold(subSampleThresholdSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type subSampleSize(subSampleSizeSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type subSampleIterations(subSampleIterationsSEXP);
    rcpp_result_gen = Rcpp::wrap(cppNoisyScamp(rawDataMatrix, dipT, clusterLB, repeatsAllowed, maxSearchDepth, maxClusterNum, userAnnotations, maxNumberOfGates, randomSearch, randomResidualSearch, finalAnnotationQs, numThreadsRequested, useRestrictedValue, restrictedValueMatrix, useForestValues, forestValues, numberOfScampIterations, outputDirectory, verboseOutput, maxSearchTime, debugScampRun, gaussianScale, randomSeed, depthScoreThreshold, subSampleThreshold, subSampleSize, subSampleIterations));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scamp_cppNoisyScamp", (DL_FUNC) &_scamp_cppNoisyScamp, 27},
    {NULL, NULL, 0}
};

RcppExport void R_init_scamp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
