# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

addNoiseToDataVector <- function(dataVector, scaleGaussian, rSeed) {
    .Call('_scamp_addNoiseToDataVector', PACKAGE = 'scamp', dataVector, scaleGaussian, rSeed)
}

cppNoisyScamp <- function(rawDataMatrix, dipT, clusterLB, repeatsAllowed, maxSearchDepth, maxClusterNum, userAnnotations, maxNumberOfGates, randomSearch, randomResidualSearch, finalAnnotationQs, numThreadsRequested, useRestrictedValue, restrictedValueMatrix, useFixedAnnotationBoundaries, fixedAnnBdrys, numberOfScampIterations, outputDirectory, verboseOutput, maxSearchTime, debugScampRun, gaussianScale, randomSeed) {
    .Call('_scamp_cppNoisyScamp', PACKAGE = 'scamp', rawDataMatrix, dipT, clusterLB, repeatsAllowed, maxSearchDepth, maxClusterNum, userAnnotations, maxNumberOfGates, randomSearch, randomResidualSearch, finalAnnotationQs, numThreadsRequested, useRestrictedValue, restrictedValueMatrix, useFixedAnnotationBoundaries, fixedAnnBdrys, numberOfScampIterations, outputDirectory, verboseOutput, maxSearchTime, debugScampRun, gaussianScale, randomSeed)
}

doubleDip <- function(x) {
    .Call('_scamp_doubleDip', PACKAGE = 'scamp', x)
}

singleDip <- function(x) {
    .Call('_scamp_singleDip', PACKAGE = 'scamp', x)
}

tripleDip <- function(x) {
    .Call('_scamp_tripleDip', PACKAGE = 'scamp', x)
}

tsGates <- function(xVec, modePrior) {
    .Call('_scamp_tsGates', PACKAGE = 'scamp', xVec, modePrior)
}

